In [2]:
import numpy as np
from matplotlib import pyplot as plt
from my_keras import activations, models, losses, metrics, regularizers, layers, optimizers

In [3]:
X_train = np.array([[-1, -1],
                    [-1, 1],
                    [1, -1],
                    [1, 1]], dtype=float)

y_train = np.array([[-1], [1], [1], [-1]], dtype=float)

X_train = np.hstack((np.ones((X_train.shape[0], 1)), X_train))

n_features = X_train.shape[1]

print(X_train.shape, y_train.shape)

(4, 3) (4, 1)


Arquitectua 1\
![circuito 1](img/61.png)

In [3]:
model = models.Network()

reg = regularizers.L2(lambda_=0) 

In [4]:
model.add(layers.Input(n_features, reg=reg))
model.add(layers.Dense(2, activation=activations.tanh(), reg=reg), scale=1)
model.add(layers.LastLayer(1, activation=activations.tanh()), scale=1)
model.printLayers()

Layer 0: <class 'my_keras.layers.Input'>
Layer 1: <class 'my_keras.layers.Dense'>
Layer 2: <class 'my_keras.layers.LastLayer'>


In [5]:
model.fit(X_train, y_train, loss=losses.MSE_XOR(), 
          opt=optimizers.SGD(alpha=.1), epochs=5000, batch_size=None)

Epoch: 0, Train loss: 0.6173076785000271
Epoch: 5000, Train loss: 0.3706719807556353
Epoch: 10000, Train loss: 0.5019790845666735
Epoch: 15000, Train loss: 0.0013297875860519847
Epoch: 20000, Train loss: 0.00030076535255825574
Epoch: 25000, Train loss: 0.00016990525457977862
Epoch: 30000, Train loss: 0.00011832422990425606
Epoch: 35000, Train loss: 9.077079341454163e-05
Epoch: 40000, Train loss: 7.364499504483421e-05
Epoch: 45000, Train loss: 6.197577474890219e-05


In [6]:
acc = metrics.acc_XOR(model.predict(X_train), y_train)
acc
model.predict(X_train)

array([[-0.99087594],
       [ 0.9882353 ],
       [ 0.9888992 ],
       [-0.9908761 ]])

In [22]:
#Que pasa si le doy solo 2 ejemplos de train?

X_train2 = X_train[2:, :]
y_train2 = y_train[2:]

model = models.Network()

reg = regularizers.L2(lambda_=0.001) 

model.add(layers.Input(n_features, reg=reg))
model.add(layers.Dense(2, activation=activations.tanh(), reg=reg), scale=1)
model.add(layers.LastLayer(1, activation=activations.tanh()), scale=1)
model.printLayers()

Layer 0: <class 'my_keras.layers.Input'>
Layer 1: <class 'my_keras.layers.Dense'>
Layer 2: <class 'my_keras.layers.LastLayer'>


In [23]:
model.fit(X_train, y_train, loss=losses.MSE_XOR(), 
          opt=optimizers.SGD(alpha=.1), epochs=20000, batch_size=None)

Epoch: 0, Train loss: 0.8019135614019528
Epoch: 2000, Train loss: 0.012419431229082758
Epoch: 4000, Train loss: 0.012698591301795407
Epoch: 6000, Train loss: 0.012986366798615218
Epoch: 8000, Train loss: 0.013146039633448531
Epoch: 10000, Train loss: 0.013229086257784385
Epoch: 12000, Train loss: 0.013271755652194302
Epoch: 14000, Train loss: 0.013293603153676132
Epoch: 16000, Train loss: 0.013304769083482609
Epoch: 18000, Train loss: 0.013310468131408784


In [26]:
#los aprende!
model.predict(X_train[0:2,:])

array([[-0.92526526],
       [ 0.91251755]])

Arquitectura 2\
![circuito 2](img/62.png)

In [29]:
model2 = models.Network()
reg2 = regularizers.L2(lambda_=0)

model2.add(layers.Input(n_features, reg=reg2))
model2.add(layers.Dense(1, activation=activations.tanh(), reg=reg2), scale=1)
model2.add(layers.ConcatInput(1, 1, n_features))
model2.add(layers.Dense(3, activation=activations.tanh(), reg=reg2), scale=1)
model2.add(layers.LastLayer(1, activation=activations.linear()), scale=1)
model2.printLayers()

Layer 0: <class 'my_keras.layers.Input'>
Layer 1: <class 'my_keras.layers.Dense'>
Layer 2: <class 'my_keras.layers.ConcatInput'>
Layer 3: <class 'my_keras.layers.Dense'>
Layer 4: <class 'my_keras.layers.LastLayer'>


In [30]:
model2.fit(X_train, y_train, loss=losses.MSE_XOR(), 
          opt=optimizers.SGD(alpha=.01), epochs=50000, batch_size=None)

Epoch: 0, Train loss: 0.8399831542171221
Epoch: 5000, Train loss: 0.00043432265752976534
Epoch: 10000, Train loss: 4.72943921515984e-08
Epoch: 15000, Train loss: 5.1611722476061575e-12
Epoch: 20000, Train loss: 5.632447252520965e-16
Epoch: 25000, Train loss: 6.146784533588108e-20
Epoch: 30000, Train loss: 6.713404048673036e-24
Epoch: 35000, Train loss: 4.8308609240570355e-27
Epoch: 40000, Train loss: 4.8308609240570355e-27
Epoch: 45000, Train loss: 4.8308609240570355e-27


In [31]:
acc = metrics.acc_XOR(model2.predict(X_train), y_train)
acc
model2.predict(X_train)

array([[-1.],
       [ 1.],
       [ 1.],
       [-1.]])